### ISSUE TITLE
Cannot successfully install

### ISSUE THREAD

**Issue by alecvn** [duvholt/i3-pager#3]
Hi

I'm having trouble installing this package on Ubuntu 18.04.  There were several Qt development packages that needed to be installed first, and after that, this command `cmake -DCMAKE_INSTALL_PREFIX=$(kf5-config --prefix)  -B build .` still fails because of some complication with the nested repo `i3ipc++`.

Any chance the installation instructions needs an update?

**Comment by duvholt** [comment]
The installation instructions aren't very complete unfortunately. One potential source of error is that you didn't clone the project with submodules. This can be done be either adding `--recurse-submodules` to `git clone` or by running `git submodule update --init --recursive` in an already cloned project. I'll add this to the readme as it's not exactly obvious.
If that doesn't fix it it would be very helpful if you pasted the error output you get while compiling.

I don't use Ubuntu so I'm not sure exactly which packages are required so if you happen to have a list I can add that to the readme as well.

**Comment by alecvn** [comment]
Thanks for the quick response, I will try the recursive clone tonight and compile the requirements I had to install that weren't mentioned in the install instructions.

**Comment by duvholt** [comment]
Readme has been updated with the recurse submodules option thanks to @SimonBrandner
