### ISSUE TITLE
Feature request : the plasmoid needs light mode

### ISSUE THREAD

**Issue by ascesh** [duvholt/i3-pager#4]
Hi ...

The text in the plasmoid seems to work only on dark plasma themes...
on light themes ..text is not readable ..see sample below

![Screenshot_20200820_013457](https://user-images.githubusercontent.com/1710612/90683925-f4de6f00-e284-11ea-84fd-dc16ec84cdac.png)

_Side note : great work ! 
am able to finally stop using polybar because of this pager
as the native KDE pager never displays the urgent workspace indicator ._

**Comment by duvholt** [comment]
I'll see if I can fix this today. Is there anything other than the font color that is unreadable?

Side note: I also originally used polybar, but with a hacky setup where I had a transparent polybar window on top of the plasma panel. It kinda worked, but the user experience was suboptimal.

**Comment by duvholt** [comment]
Text color should use plasma theme colors now.

I fixed hardcoding of font family and font size as well.

**Comment by duvholt** [comment]
Closing this as light mode support has been added. I can reopen the issue if there are still some issues with light mode/theme support.

**Comment by ascesh** [comment]
tested on latest ..works fine...
thanks !
